mod client;
mod edition;

pub use client::Client;
pub use client::Entity;
pub use client::CoverSize;
pub use client::ApiType;

pub use edition::Edition;
pub use edition::Author;
pub use edition::ByStatement;
pub use edition::Created;
pub use edition::EditionName;
pub use edition::Identifiers;
pub use edition::Language;
pub use edition::LastModified;
pub use edition::LatestRevision;
pub use edition::Notes;
pub use edition::NumberOfPages;
pub use edition::Pagination;
pub use edition::PhysicalDimensions;
pub use edition::PhysicalFormat;
pub use edition::PublishDate;
pub use edition::Revision;
pub use edition::Subtitle;
pub use edition::TableOfContents;
pub use edition::Title;
pub use edition::Type;
pub use edition::Weight;
pub use edition::Work;
